### PR TITLE
Estimate clevel

### PR DESCRIPTION
**Pull request by Jiaqi-beep**
Include function estimate_levels to estimate lower bound, upper bound and steps of the levels of contour lines and filled contours.

### CODE REVIEW

**Review by anissa111 — APPROVED** [review]
This looks good! @michaelavs, when you get back from PTO, what are your thoughts on merging this before merging contourf fully in?

**Comment by erogluorhan** [comment]
@michaelavs Any update here?

**Comment by michaelavs** [comment]
> I believe this PR should be wrapped in with Erin's #40, @erinlincoln @michaelavs, thoughts?

I think that would be fine! I double checked that the PRs (407, 409, 410) in examples weren't depending on this being merged first and it looks good to go on that side

**Comment by anissa111** [comment]
This was included in #40, closing.

**Pull request closed without merging**
