### PR TITLE
fix and update truncate_colormap

### LINKED ISSUE #124: truncate_colormap parameter n isn't working as intended
While I was updating `truncate_colormap` in viz, I noticed the parameter `n` wasn't working as intended.  It would need to be specified as a parameter in `mpl.colors.LinearSegmentedColormap.from_list` rather than in `np.linspace` in order to specify the number of color values in the new colormap.

I thought maybe this was related to a change in matplotlib, but that doesn't appear to be the case.

Interestingly there are workaround(s) for this in the examples gallery.  For example, in [NCL_vector_4.py](https://geocat-examples.readthedocs.io/en/latest/gallery/Vectors/NCL_vector_4.html) the colormap is truncated with n=16, but this doesn't work so then `get_cmap` is used to re-register it and give it 16 levels as desired or when using `contourf` the number of levels is assigned so it doesn't matter that `truncate_colormap` doesn't work as intended.  

We should probably also clean up the colormap registration and deprecated colormap functions in examples.  I'll log an issue over there.

### PR DESCRIPTION
**Pull request by kafitzgerald**
Update `truncate_colormap` to use new [matplotlib colormap registration](https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.register_cmap) and add an option to force an overwrite of an already registered colormap to partially address issues #112 and #104.  

~~**Note:** This will only work back to v3.5 of matplotlib.  See the [release notes](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.5.0.html#colors-and-colormaps).  We could address this in a different way that would allow for more backwards compatibility, but it's not recommended moving forward.  And if we move forward with this we'll need to update the dependency list, which I haven't done yet.  It'd be a pretty narrow range of versions right now as well with the version pin mentioned in #104 and to get rid of that we still need to address the external cmaps package issues or bring the NCL colormaps into viz.~~  
Added some error checking to make this backward compatible.

Additionally, update `truncate_colormap` to return a colormap with n quantization levels as designed.  Closes #124.

I still think we should probably deprecate this function and do something slightly different when or after we fully address #112 and #104, but this will keep the function working w/ newer matplotlib versions.

### CODE REVIEW

**Comment by kafitzgerald** [comment]
Another option could be to remove deprecate and remove this function and use the equivalent [CMasher function](https://cmasher.readthedocs.io/api/cmasher.html?#cmasher.get_sub_cmap) in the examples where we need it.

**Comment by kafitzgerald** [comment]
> Another option could be to deprecate and remove this function and use the equivalent [CMasher function](https://cmasher.readthedocs.io/api/cmasher.html?#cmasher.get_sub_cmap) in the examples where we need it.

It looks like there's an open issue https://github.com/1313e/CMasher/issues/43 to address the matplotlib updates, but it hasn't happened yet.  So not sure this would be a good option.

**Review by jukent — APPROVED** [review]
Great thanks @kafitzgerald this seems like a good fix to our immediate problem.

**Review by anissa111 — APPROVED** [review]
This looks like a good fix while y'all sort out your larger cmap issues!

**Comment by jukent** [comment]
Wait @kafitzgerald was this your first GeoCAT merged PR? Congratulations! 🎉

**Comment by kafitzgerald** [comment]
It was!  😄

**Comment by erogluorhan** [comment]
> It was! 😄

🎉 Congrats; great contribution!

**Pull request merged**
