### PR TITLE
Add three functions to util

### PR DESCRIPTION
**Pull request by mnlevy1981**
1. `nclize_axis()` -- produces axes that look more like NCL plots (tick marks on
   all four sides, major and minor ticks, etc)
2. `add_lat_lon_ticklabels()` -- Longitudes are labelled with E / W designator
   (e.g. `30 W`, `50 E`) with default of `0` and `180` but optional arguments
   to add direction there as well. Similarly, latitudes have N / S designator
   such as `30 S` or `50 N`. Equator is `0` with no directional indication.
3. `truncate_colormap()` -- As the name suggestions, truncates the colors
   available from a given map.

Thanks to @dcherian for putting these functions together!

### CODE REVIEW

**Comment by mnlevy1981** [comment]
Two additional notes:

1. I've been using these functions in my code with

   ```
   import geocat.viz as gcv

   gcv.util.nclize_axis(ax)
   ```

   I'm not sure if that's the optimal way to include the functions, but it seemed like a good start.

1. I added docstrings to all the functions in `util.py`, but I didn't follow any sort of convention in doing so.

**Comment by mnlevy1981** [comment]
Oh, and a third thing: I moved all `import` statements in `util.py` inside the function calls. Is that the right way to do it, or should the imports all be right up top?

```python
def nclize_axis(ax, minor_per_major=3):

    import matplotlib.ticker as tic

def add_lat_lon_ticklabels(ax, zero_direction_label=False, dateline_direction_label=False):

    from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter

def truncate_colormap(cmap, minval=0.0, maxval=1.0, n=100, name=None):

    import numpy as np
    import matplotlib as mpl
    from matplotlib import cm
```

vs

```python
import matplotlib.ticker as tic
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
import numpy as np
import matplotlib as mpl
from matplotlib import cm

def nclize_axis(ax, minor_per_major=3):

def add_lat_lon_ticklabels(ax, zero_direction_label=False, dateline_direction_label=False):

def truncate_colormap(cmap, minval=0.0, maxval=1.0, n=100, name=None):

```

**Comment by khallock** [comment]
Thanks @mnlevy1981 and @dcherian for the contribution!

> Two additional notes:
> 
> 1. I've been using these functions in my code with
>    ```
>    import geocat.viz as gcv
>    
>    gcv.util.nclize_axis(ax)
>    ```
>    
>    I'm not sure if that's the optimal way to include the functions, but it seemed like a good start.

I like this idea, but we may want to adopt a consistent name-shortening convention across GeoCAT projects. Following this shortening scheme `geocat.comp` would end up as `gcc`, which seems like a questionable decision.

> 2. I added docstrings to all the functions in `util.py`, but I didn't follow any sort of convention in doing so.

Great! Thanks for adding docstrings!

> Oh, and a third thing: I moved all import statements in util.py inside the function calls. Is that the right way to do it, or should the imports all be right up top?

My gut instinct on this is that putting import statements inside function calls is good _if the import is only used once in the entire file by that function_, otherwise I'd prefer to keep them all at the top of the file. That said, I'm not strongly committed to this stance and the modifications you made look good as-is.

**Comment by mnlevy1981** [comment]
@khallock 

> My gut instinct on this is that putting import statements inside function calls is good _if the import is only used once in the entire file by that function_, otherwise I'd prefer to keep them all at the top of the file.

I think there are only two imports that are duplicated (`numpy` and `matplotlib.cm` are used by both `truncate_colormap()` and `make_byr_cmap()`) and that'll resolve itself if `make_byr_cmap()` is removed in favor of `cmaps.BlueYellowRed`. However, additional functions may be added to `util` and it will get a little unwieldy to track which imports belong where... so maybe they should just all be at the top for extensibility? The counterpoint being that maybe we will want to refactor `util` in the future and it'll be much easier to bring the `import`s along with the function. So a long-winded way of saying I like "the modifications you made look good as-is" but won't treat it as the end-all / be-all method for importing packages in the future.

**Pull request merged**
