### PR TITLE
Force cmap

### PR DESCRIPTION
**Pull request by pilotchute**

### CODE REVIEW

**Review by anissa111 — COMMENTED** [review]
This isn't working for me. Here's what I did to test it:
1. pip installed geocat-viz from this branch in a new environment
2. manually installed the minimum required packages to run `NCL_panel_5.py`
3. ran the example (failed with same error)
4. ran with debug, traced down to -viz function to make sure the `override_buildin=True` was being used (and it was)

The upstream geocat-examples tests are passing on this PR because they're inheriting the geocat-examples matplotlib pin

**Comment by jukent** [comment]
Is this related to #105 or #112?

**Comment by jukent** [comment]
Adding invalid label until we've investigated other methods of dealing with the cmap issue or @anissa111 's concerns are addressed.

**Comment by kafitzgerald** [comment]
Looks like this PR relates to this issue over in examples: https://github.com/NCAR/geocat-examples/issues/494

Similar to issue #112 on this repo.

**Pull request closed without merging**
