### PR TITLE
Move get_skewt_vars from geocat-comp to geocat-viz

### PR DESCRIPTION
**Pull request by hCraker**
This is part of the work done for the module restructuring issue in geocat-comp https://github.com/NCAR/geocat-comp/issues/248

### CODE REVIEW

**Comment by anissa111** [comment]
I thought this was good to go, but I'm seeing an error [here](https://github.com/NCAR/geocat-viz/actions/runs/3152778014/jobs/5223290877#step:6:1105) that does not seem to be appearing in the nightly geocat-examples errors. Interestingly, it is coming from one of the comp examples, ``linint2_example``, and I'm not sure why this PR would cause this issue. 

I'm pretty sure this PR is good to go, but I don't think we should merge until the tests are cleaned up just to be sure.

**Comment by anissa111** [comment]
It looks like docs is trying to run with 3.11 and failing, we should be able to pin python<3.11 and be good to go if everything's good on your end, @pilotchute

**Comment by hCraker** [comment]
Now that I've pinned the python version, I'm getting this error ```sphinx.ext.autosummary.ImportExceptionGroup: no module named geocat.viz.TaylorDiagram```. I'm looking into it now, but any help is appreciated

**Comment by hCraker** [comment]
@anissa111 thanks for the help! I got too far into the weeds there.

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
