### PR TITLE
Automation

### PR DESCRIPTION
**Pull request by anissa111**
Summary of changes:
- adds `.github/workflows/upstream-examples-ci.yml` to project

This PR adds checks against the [GeoCAT-examples](https://readthedocs.org/projects/geocat-examples/) repository by generating its sphinx builds

### CODE REVIEW

**Review by erogluorhan — COMMENTED** [review]
Thanks for putting this together! I believe one thing needs to be corrected as follows:

It looks like this workflow clones GeoCAT-examples, then creates a conda environment using its yml file, after that, directly runs `make html`. Such a flow tests things against whatever the version of GeoCAT-viz (e.g. latest or specifically pinned version) being installed through conda via using GeoCAT-examples repo's yml file. However, we would like this workflow to test GeoCAT-examples against the latest code changes hapenning in GeoCAT-viz (i.e. maybe a pull-request or something else). This is in order to guarantee if we release a newer version of GeoCAT-viz with such changes on conda, it wouldn't break GeoCAT-examples. 

That said, I believe we should have something like the following code in between conda env creation and `make html` in the workflow:

```
- name: Install geocat-viz
        run: |
         python -m pip install --no-deps --ignore-installed -vv .
```

**Comment by anissa111** [comment]
@erogluorhan you're totally right, thanks for the catch! Note that the checks on this PR will fail because the geocat-examples is not set up to run with the newest version of -viz yet. If you look at the `make html` step, it has updated to the most recent changes as opposed to the pin version of the commit that "passes"

**Comment by erogluorhan** [comment]
> Note that the checks on this PR will fail because the geocat-examples is not set up to run with the newest version of -viz yet. If you look at the `make html` step, it has updated to the most recent changes as opposed to the pin version of the commit that "passes"

Yes, that was expected! Apparently not for this time (as the changes in -viz were huge and expected to break -examples), but for the future, this automation will work well for us to see if we are not breaking things upstream! 

So, moving forward, would you like me to approve it as is, then you can start with getting -examples to work with latest -viz version?

**Review by erogluorhan — APPROVED** [review]

**Comment by anissa111** [comment]
> Yes, that was expected! Apparently not for this time (as the changes in -viz were huge and expected to break -examples), but for the future, this automation will work well for us to see if we are not breaking things upstream!
> 
> So, moving forward, would you like me to approve it as is, then you can start with getting -examples to work with latest -viz version?

Yes, that sounds good!

**Pull request merged**
