### PR TITLE
version bump for 2022.02.0 release

### PR DESCRIPTION
**Pull request by anissa111**

### CODE REVIEW

**Comment by erogluorhan** [comment]
I am happy to approve this if you tested the recent developments here against GeoCAT-examples.

**Comment by anissa111** [comment]
> I am happy to approve this if you tested the recent developments here against GeoCAT-examples.

We really need an automated way to do this. Let me try to set that up real quick.

**Comment by erogluorhan** [comment]
> 

Agree, that would be great!

**Comment by anissa111** [comment]
Marking as draft so I can look in to automatic testing

**Comment by anissa111** [comment]
I'm going to close this as the version number is now out of date

**Pull request closed without merging**
