### PR TITLE
add generate_2d_array

### PR DESCRIPTION
**Pull request by Jiaqi-beep**
Add function generate_2d_array from https://github.com/NCAR/pyngl/blob/develop/src/ngl/__init__.py

This is the equivalent of ncl function [generate_2d_array](https://www.ncl.ucar.edu/Document/Functions/Built-in/generate_2d_array.shtml)

### CODE REVIEW

**Comment by anissa111** [comment]
Huh, I'm not actually sure where this function belongs. Do we currently have any functions from pyngl implemented anywhere? To my knowledge, we don't have any actual NCL function implemented anywhere on the visualization side of GeoCAT. @erogluorhan @michaelavs what do you think?

**Comment by erogluorhan** [comment]
Couldn't numpy or other packages be used to achieve what NCL's custom  [generate_2d_array](https://www.ncl.ucar.edu/Document/Functions/Built-in/generate_2d_array.shtml) does?

**Comment by anissa111** [comment]
> Couldn't numpy or other packages be used to achieve what NCL's custom [generate_2d_array](https://www.ncl.ucar.edu/Document/Functions/Built-in/generate_2d_array.shtml) does?

Also a good point. Maybe instead of implementing this as a function we could add examples to the gallery that demonstrate how to generate random 2d data like NCL did?

**Comment by Jiaqi-beep** [comment]
> > Couldn't numpy or other packages be used to achieve what NCL's custom [generate_2d_array](https://www.ncl.ucar.edu/Document/Functions/Built-in/generate_2d_array.shtml) does?
> 
> Also a good point. Maybe instead of implementing this as a function we could add examples to the gallery that demonstrate how to generate random 2d data like NCL did?

I think this function from pyngl implements the original function exactly, at least that's how the data seems like. I tried to look for Numpy's way of generating 2d data but I haven't found one with the exact functionality as the NCL one, with lows and highs specified. np.random.randint takes in lows and highs but generate integers instead of float. I can look into this more, but do you @anissa111 @erogluorhan happen to know which function(s) would work?

Also I thought of adding this because [panel_35](https://geocat-examples.readthedocs.io/en/latest/gallery/Panels/NCL_panel_35.html#sphx-glr-gallery-panels-ncl-panel-35-py) uses this function and I looked into the [PR](https://github.com/NCAR/GeoCAT-examples/pull/71) for this and people seem to be suggesting adding it into comp.

**Comment by erogluorhan** [comment]
I mean, the implementation of `generate_2d_array` from PyNGL has already been included under [NCL_panel_35](https://github.com/NCAR/GeoCAT-examples/blob/main/Plots/Panels/NCL_panel_35.py) here, and it works. 

However, that implementation feels some room to be improved. Though, this is a specialized function that generates pseudo random numbers using a sum of exponentials with also using both numbers and values of lows and highs. 

@Jiaqi-beep : Yes, a while ago we discussed adding this function to geocat-comp. It might still go that way if not only panel_35 but also other people/functions rely on such a generator. Otherwise, its PyNGL-equivalent implementation is already under [NCL_panel_35](https://github.com/NCAR/GeoCAT-examples/blob/main/Plots/Panels/NCL_panel_35.py). So, do you mean it should better be moved out of that script, maybe to make the script much light weight?

**Comment by Jiaqi-beep** [comment]
> I mean, the implementation of `generate_2d_array` from PyNGL has already been included under [NCL_panel_35](https://github.com/NCAR/GeoCAT-examples/blob/main/Plots/Panels/NCL_panel_35.py) here, and it works. However, that implementation feels like some room is possible for improvement (as I suggested numpy or others previously). Though, this is a specialized function that generates pseudo random numbers using a sum of exponentials with also using both numbers and values of lows and highs.
> 
> @Jiaqi-beep : Yes, a while ago we discussed adding this function to geocat-comp. It might still go that way if not only panel_35 but also other people/functions rely on such a generator. Otherwise, its PyNGL-equivalent implementation is already under [NCL_panel_35](https://github.com/NCAR/GeoCAT-examples/blob/main/Plots/Panels/NCL_panel_35.py). So, do you mean it should better be moved out of that script (maybe into GeoCAT-viz) so that our panel_35 script could be much lighter weight?

Yes, I was wondering if we can incorporate it into Comp to make the script much shorter! For a moment my mind broke down and put it in here. But I'm not sure how common/necessary to put it into comp.

**Pull request closed without merging**
